version: "3.9"

services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django-app:
    build: .
    command: >
      sh -c "
             python manage.py createsuperuserwithpassword --username admin --password admin --email admin@example.org --preserve &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django-app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    links:
      - db:db

volumes:
  db_volume:
    external: true